apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Values.global.namespace }}
  labels:
    chart: {{ include "cinemaabyss.chart" . }}
    release: {{ .Release.Name }}
data:
  # Database configuration
  DB_HOST: "{{ .Values.database.host }}"
  DB_PORT: "{{ .Values.database.port }}"
  DB_NAME: "{{ .Values.database.name }}"
  DB_USER: "{{ .Values.database.user }}"

  # Service URLs
  MONOLITH_URL: "{{ .Values.proxyService.env.MONOLITH_URL }}"
  MOVIES_SERVICE_URL: "{{ .Values.proxyService.env.MOVIES_SERVICE_URL }}"
  EVENTS_SERVICE_URL: "{{ .Values.proxyService.env.EVENTS_SERVICE_URL }}"
  
  # Strangler Fig configuration
  GRADUAL_MIGRATION: "{{ .Values.proxyService.env.GRADUAL_MIGRATION }}"
  MOVIES_MIGRATION_PERCENT: "{{ .Values.proxyService.env.MOVIES_MIGRATION_PERCENT }}"

  # Kafka configuration
  KAFKA_BROKER: "{{ .Values.eventsService.env.KAFKA_BROKER }}"