{{- if .Values.imagePullSecrets.dockerconfigjson }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-dockerconfig
  namespace: {{ .Values.global.namespace }}
  labels:
    chart: {{ include "cinemaabyss.chart" . }}
    release: {{ .Release.Name }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.imagePullSecrets.dockerconfigjson | quote }}
{{- end }}