apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Values.global.namespace }}
  labels:
    chart: {{ include "cinemaabyss.chart" . }}
    release: {{ .Release.Name }}
type: Opaque
data:
  # Base64 encoded values
  # echo -n "postgres_password" | base64
  DB_PASSWORD: {{ .Values.postgresql.auth.postgresPassword | b64enc | quote }}