apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogewoJCQkiYXV0aCI6ICJhMmx5WVdaeWIyMXpaV0U2WjJod1gydzJWRlJLTVROeFZUTlBXamhVUlRoWFUxUlFNVk52T0c5VWVIRjZWakJCWlhNMmJBPT0iCgkJfQoJfSwKCSJjcmVkc1N0b3JlIjogImRlc2t0b3AiLAoJImN1cnJlbnRDb250ZXh0IjogImRlc2t0b3AtbGludXgiCn0K
type: kubernetes.io/dockerconfigjson
